[package]
name = "nova-sql"
edition.workspace = true
version.workspace = true
description = "SQL database adapter and helpers for Nova (SeaORM integration)"
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["microservices", "axum", "web", "nova"]
categories = ["web-programming::http-server"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
axum.workspace = true
async-trait.workspace = true
serde.workspace = true
sea-orm = { workspace = true, features = ["sqlx-sqlite", "runtime-tokio-rustls"] }
sea-orm-migration.workspace = true
sea-query.workspace = true
nova-boot = { path = "../../nova-boot", version = "0.1.0" }
serde_json.workspace = true
tokio.workspace = true
redis = { workspace = true, features = ["aio", "tokio-comp"] }