[workspace]
members = [
    "crates/nova-core", "crates/nova-macros", "crates/nova-sql", "example/demo",
]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
# The Web Engine
axum = "0.8"
tokio = { version = "1.0", features = ["full"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["trace", "cors"] }
inventory = "0.3"

# Serialization & Utilities
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
async-trait = "0.1"

# Database support (optional)
sea-orm = "1.1"
sea-orm-migration = "1.1"
sea-query = "0.32"

# Internal Macros
syn = { version = "2.0", features = ["full"] } 
quote = "1.0"                                 
proc-macro2 = "1.0"


redis = "0.23"