[workspace]
members = [
    "crates/nova-boot",
    "crates/nova-boot-macros",
    "crates/nova-boot-middleware",
    "crates/nova-boot-observability",
    "crates/nova-boot-resilience-store",
    "crates/plugins/*",
    "crates/discovery/*",
    "crates/nova-boot-client",
    "crates/nova-boot-gateway",
    "crates/nova-boot-auth",
    "crates/nova-boot-cli",
    "crates/nova-boot-test",
    "crates/nova-boot-data-patterns",
    "example/demo", "crates/nova-boot-tasks", 
]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.1.1"
license = "MIT"
repository = "https://github.com/nova-boot-rs/nova"

[workspace.dependencies]
# The Web Engine
axum = "0.8"
axum-server = "0.8"
tokio = { version = "1.0", features = ["full"] }
tokio-rustls = "0.26"
tower = "0.5"
tower-http = { version = "0.6", features = ["trace", "cors"] }
inventory = "0.3"

# Serialization & Utilities
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
async-trait = "0.1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
etcd-client = "0.14"

# Database support (optional)
sea-orm = "1.1"
sea-orm-migration = "1.1"
sea-query = "0.32"

# Internal Macros
syn = { version = "2.0", features = ["full"] } 
quote = "1.0"                                 
proc-macro2 = "1.0"


redis = "0.23"

# Internal crates
nova-boot-macros = { path = "crates/nova-boot-macros", version = "0.1.1" }
nova-boot-resilience-store = { path = "crates/nova-boot-resilience-store", version = "0.1.1" }
nova-boot = { path = "crates/nova-boot", version = "0.1.1" }
nova-boot-middleware = { path = "crates/nova-boot-middleware", version = "0.1.1" }
nova-boot-observability = { path = "crates/nova-boot-observability", version = "0.1.1" }
nova-boot-client = { path = "crates/nova-boot-client", version = "0.1.1" }
nova-boot-gateway = { path = "crates/nova-boot-gateway", version = "0.1.1" }
nova-boot-auth = { path = "crates/nova-boot-auth", version = "0.1.1" }
nova-boot-cli = { path = "crates/nova-boot-cli", version = "0.1.1" }
nova-boot-test = { path = "crates/nova-boot-test", version = "0.1.1" }
nova-boot-data-patterns = { path = "crates/nova-boot-data-patterns", version = "0.1.1" }
nova-boot-discovery-static = { path = "crates/discovery/nova-boot-discovery-static", version = "0.1.1" }
nova-boot-discovery-consul = { path = "crates/discovery/nova-boot-discovery-consul", version = "0.1.1" }
nova-boot-discovery-etcd = { path = "crates/discovery/nova-boot-discovery-etcd", version = "0.1.1" }
nova-boot-tasks = { path = "crates/nova-boot-tasks", version = "0.1.1" }
nova-boot-sql = { path = "crates/plugins/nova-boot-sql", version = "0.1.1" }
nova-boot-nosql = { path = "crates/plugins/nova-boot-nosql", version = "0.1.1" }
nova-boot-messaging = { path = "crates/plugins/nova-boot-messaging", version = "0.1.1" }
nova-boot-graphql = { path = "crates/plugins/nova-boot-graphql", version = "0.1.1" }

