[package]
name = "demo"
edition.workspace = true
version.workspace = true

[dependencies]
axum = "0.8"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
nova-core = { path = "../../crates/nova-core" }
nova-middleware = { path = "../../crates/nova-middleware" }
nova-observability = { path = "../../crates/nova-observability" }
nova-sql = { path = "../../crates/plugins/nova-sql" }
sea-orm = { version = "1", features = ["sqlx-sqlite", "runtime-tokio-rustls"] }
serde_json = "1.0"