[package]
name = "demo"
edition.workspace = true
version.workspace = true
description = "Small demo application showing Nova integrations"
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["microservices", "axum", "web", "nova"]
categories = ["web-programming::http-server"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
axum = "0.8"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
nova-boot = { path = "../../crates/nova-boot" }
nova-boot-middleware = { path = "../../crates/nova-boot-middleware" }
nova-boot-observability = { path = "../../crates/nova-boot-observability" }
nova-boot-sql = { path = "../../crates/plugins/nova-boot-sql" }
sea-orm = { version = "1", features = ["sqlx-sqlite", "runtime-tokio-rustls"] }
serde_json = "1.0"