[package]
name = "nova-discovery-etcd"
edition.workspace = true
version.workspace = true
description = "etcd discovery adapter for Nova"
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["microservices", "axum", "web", "nova"]
categories = ["web-programming::http-server"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
async-trait = { workspace = true }
etcd-client = { workspace = true }
nova-core = { path = "../../nova-core" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
