[package]
name = "nova-boot-discovery-static"
edition.workspace = true
version.workspace = true
description = "Static discovery adapter for Nova"
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["microservices", "axum", "web", "nova"]
categories = ["web-programming::http-server"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
nova-boot.workspace = true
async-trait.workspace = true
tokio = { workspace = true, features = ["sync", "rt", "macros"] }
