use nova_boot_sql::NovaSql;
use sea_orm::DbErr;
use sea_orm_migration::prelude::{MigrationTrait, MigratorTrait};
use std::time::Duration;

struct DummyMigrator;

impl MigratorTrait for DummyMigrator {
    fn migrations() -> Vec<Box<dyn MigrationTrait>> {
        Vec::new()
    }
}

#[tokio::main]
async fn main() {
    // Demonstrates running migrations with retry logic. In real apps you
    // would supply a real migrator generated by `sea-orm-cli`.
    let sql = NovaSql::connect("sqlite::memory:", false).await;

    match sql
        .run_migrations_with_retry::<DummyMigrator>(1, Duration::from_millis(100))
        .await
    {
        Ok(()) => println!("migrations applied (or none to run)"),
        Err(DbErr::Custom(e)) => eprintln!("migration failed: {}", e),
        Err(e) => eprintln!("migration error: {:?}", e),
    }
}
