[package]
name = "nova-boot-discovery-dns"
edition.workspace = true
version.workspace = true
description = "DNS-based discovery adapter for Nova"
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["microservices", "axum", "web", "nova"]
categories = ["web-programming::http-server"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
