[package]
name = "nova-discovery-consul"
edition.workspace = true
version.workspace = true
description = "Consul discovery adapter for Nova"
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["microservices", "axum", "web", "nova"]
categories = ["web-programming::http-server"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
nova-core = { path = "../../nova-core" }
async-trait.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
