[package]
name = "nova-graphdb"
edition.workspace = true
version.workspace = true

[dependencies]
nova-core = { path = "../../nova-core" }
tokio.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
