[package]
name = "nova-boot-client"
edition.workspace = true
version.workspace = true
description = "Client helpers for communicating with Nova services"
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["microservices", "axum", "web", "nova"]
categories = ["web-programming::http-server"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
